#!/bin/bash

# bash setup
cp -a \

	# bash setup
	.bashrc .bash_profile .profile \

	# vim setup
	.vim .vimrc .gvimrc \
	
	# tmux and inputrc
	.tmux.conf .inputrc \
	
	# git setup
	.gitconfig .gitignore "$HOME"

