#!/bin/bash
set -ue

declare dotfiles=(
	# ".profile"
	".bash_profile"
	".bashrc"
	".tmux.conf"
	".vimrc"
	".inputrc"
	".Xresources"
)

# Basic Config
echo "Linking dotfiles..."
for file in "${dotfiles[@]}"; do ln -sf "$PWD/$file" "$HOME/$file"; done

echo "Linking vim files..."

echo "Pulling package manager and color scheme..."
# vim-plug
curl -flo "$HOME/.vim/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Linking .configs..."

# Alacrity
mkdir -p "$HOME/.config/alacritty" "$HOME/.config/neofetch" "$HOME/.config/nvim"
ln -sf "$PWD/.config/alacritty/alacritty.yml" "$HOME/.config/alacritty/alacritty.yml"

# Neofetch
ln -sf "$PWD/.config/neofetch/config.conf" "$HOME/.config/neofetch/config.conf"

# Nvim
mkdir -p "$HOME/.config/nvim" || true
ln -sf "$PWD/.config/nvim/init.vim" "$HOME/.config/nvim/init.vim"

# Vifm
# mkdir -p "$HOME/.config/vifm" || true
# mkdir -p "$HOME/.config/vifm/colors/" || true
# cp -a "$PWD/.config/vifm/colors/" "$HOME/.config/vifm/colors/"
# ln -sf "$PWD/.config/vifm/vifmrc" "$HOME/.config/vifm/vifmrc"

# BitBar
mkdir -p "$HOME/.config/bitbar"|| true
ln -sf "$PWD/.config/bitbar/getip" "$HOME/.config/bitbar/getip"

echo "DONE.. Open Vim and type  ESC + :PlugInstall and install all necessary tools for vim and so on (composer, eslint, ...)"

