#!/bin/bash

declare -a dotfiles

dotfiles=(
	# Bash Config
	".profile"
	".bash_profile"
	".bashrc"

	# Miscellaneous
	".tmux.conf"
	".inputrc"

	# Git Config
	".gitconfig"
)

# Basic Config
for file in "${dotfiles[@]}"; do
	echo "Linking dotfiles..."
	ln -sf "$PWD/$file" "$HOME/$file"
done

if [[ "$1" == "vim-extended" ]]; then

	echo "Linking vim files..."
	# Setup Vimrc
	ln -sf \
		"$PWD/.vimrc" "$HOME/.vimrc" && \
		"$PWD/.gvimrc" "$HOME/.gvimrc"
	
	echo "Pulling package manager and color scheme..."
	# vim-plug
	curl -flo "$HOME/.vim/autoload/plug.vim" --create-dirs \
	    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

	# Unicon Scheme
	curl -flo "$HOME/.vim/colors/unicon.vim" --create-dirs \
		https://raw.githubusercontent.com/lukasjoc/vim-unicon/master/colors/unicon.vim

	# Skelets
	echo "Linking vim skelet files... "
	[[ -d $HOME/.vim/skels ]] || mkdir "$HOME/.vim/skels"
	for skel in .vim/skels/skel*; do
		ln -sf "$PWD/$skel" "$HOME/$skel"
	done
	echo "DONE.. Open Vim and type  ESC + :PlugInstall"
fi

