#!/bin/bash

config_dir=$HOME/.config/fish

ln -sf "$PWD/functions/fish_prompt.fish" "$config_dir/functions/fish_prompt.fish"
ln -sf "$PWD/config.fish" "$config_dir/config.fish"

# Install Plugins and Fisher if necessary
ln -sf "$PWD/fish_plugins" "$config_dir/fish_plugins"
if [[ ! -f "$config_dir/functions/fisher.fish" ]]; then
  curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fi
fisher install
